# Generated by Django 6.0.4 on 2026-05-03 20:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ra', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=80)),
                ('Turma', models.CharField(max_length=6)),
                ('Create_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_File', models.CharField(max_length=50)),
                ('Drawing_File', models.FileField(upload_to='Drawning/%Y/%m/%d')),
                ('Create_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Description', models.TextField(blank=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ForFabMetals.project')),
            ],
        ),
    ]
